services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: pass123
      MYSQL_USER: orderx
      MYSQL_PASSWORD: 123123
    volumes:
      - mysql-data:/var/lib/mysql
  
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"

  nginx:
    image: nginx:latest
    container_name: orderx-gateway
    ports:
      - 8080:80
    depends_on:
      - auth
      - products
    volumes:
      - ./nginx/index.html:/usr/share/nginx/html/index.html:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  auth:
    build: ../services/auth
    container_name: auth-service
    ports:
      - 8000:8000
    depends_on:
      - mysql
    environment:
      MYSQL_USER: orderx
      MYSQL_PASSWORD: 123123
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DB_USERS: auth_data
  
  products:
    build: ../services/products
    container_name: products-service
    ports:
      - 8001:8000
    depends_on:
      - mysql
    environment:
      MYSQL_USER: orderx
      MYSQL_PASSWORD: 123123
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DB_USERS: productsdb


volumes:
  mysql-data: